/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaApplication1;

import com.mysql.cj.x.protobuf.MysqlxDatatypes.Scalar.String;

import java.util.Date;
import oru.inf.InfDB;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcu
 */
public class Agent2{

private static InfDB idb;
private int agent_ID;
private String namn;
private String Telefon;
private String losenord;
private boolean administrator;
private Date anstallningsdatum;

    
public Agent2(String namn, String Telefon, String losenord)throws Exception {
agent_ID = new Random().nextInt(10);
this.namn = namn;
this.Telefon = Telefon;
this.losenord = losenord;
administrator = false;
anstallningsdatum = new Date();

}

 

public int getAgentID(){
return agent_ID;
}

public String getNamn(){
return namn;
}

public String getTelefon(){
return Telefon;
}

public Date getAnstallningsdatum(){
return anstallningsdatum;
}

public void bytLosenord(String nyttLosenord){
nyttLosenord = losenord;
}

public boolean getAdministrator(){
return administrator;
}

public boolean becomeAdministrator(){
administrator = true;
return administrator;
}

public String getLosenord(){
return losenord;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Agent2().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Agent2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

       
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

