/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaApplication1;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Marcu
 */
public class BytaLosenordAlien extends javax.swing.JFrame {
    private static InfDB idb;
    String hamtatIDString;
    int hamtatID;
    static Validering vemArInloggad;
    /**
     * Creates new form BytaLosenord
     * @param idb
     * @param vemArInloggad
     */
    public BytaLosenordAlien(InfDB idb, Validering vemArInloggad) {
        initComponents();
        this.setLocationRelativeTo(null);
        BytaLosenordAlien.idb = idb;
        BytaLosenordAlien.vemArInloggad = vemArInloggad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passNytt = new javax.swing.JPasswordField();
        passNuvarande = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnBytLosenord = new javax.swing.JButton();
        btnGaTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Byta lösenord");

        jLabel3.setText("Nuvarande lösenord");

        jLabel4.setText("Nytt lösenord");

        btnBytLosenord.setText("Spara");
        btnBytLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLosenordActionPerformed(evt);
            }
        });

        btnGaTillbaka.setText("Gå tillbaka till AlienMenyn");
        btnGaTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnGaTillbaka)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                            .addComponent(btnBytLosenord))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passNytt, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(passNuvarande)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(passNuvarande, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passNytt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBytLosenord)
                    .addComponent(btnGaTillbaka))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBytLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLosenordActionPerformed
        // TODO add your handling code here:
            if(Validering.finnsLosenord(passNuvarande) 
                && Validering.finnsLosenord(passNytt)
                ){
// Dubbelkollar så textfälten ej är tomma med koden ovanför som hänvisar till Valideringsklassen.
            try{
                char[] losenordArray = passNuvarande.getPassword();
                String gammalLosenord = new String(losenordArray);

                char[] nyttLosenordArray = passNytt.getPassword();
                String nyttLosenord = new String(nyttLosenordArray);

                String fraga = "SELECT losenord FROM Alien WHERE alien_id =" + "'" + vemArInloggad.getId() + "'";
                String resultat = idb.fetchSingle(fraga);
 //!!!!!! Vi skulle också kunna hämta nuvarande lösenord från Valideringsklassen istället för att köra sql-frågan ovanför.!!!!!!!
                if(gammalLosenord.equals(resultat)){
                    if(Validering.losenordMaxTecken(passNytt)){ 
                    String qSetPassword = "UPDATE alien SET losenord =" + "'" + nyttLosenord + "'" + "WHERE alien_id = " + "'" + vemArInloggad.getId() + "'";
                    idb.update(qSetPassword);
                    vemArInloggad.setNyttLosenord(nyttLosenord);
 // Anropar metoden setNyttLosenord() från inloggningValideringsklassen och ändrar personens lösenord via den klassen.
                     JOptionPane.showMessageDialog(this, "Lösenord har ändrats!");
                    }

                }
                else{
                    passNuvarande.requestFocus();
                    JOptionPane.showMessageDialog(this, "Ditt nuvarande lösenord är felaktigt!");
                }
    
            }
            catch (InfException ex){
                System.out.println("Databasfel" + ex.getMessage());
            }
            catch (Exception ex){
                System.out.println("Random fel" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnBytLosenordActionPerformed

    private void btnGaTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaTillbakaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Ditt lösenord är nu: " + vemArInloggad.getLosenord()); // Bara för att förtydliga att det nya lösenordet följer med. Kan ju tas bort.
        this.dispose();
        new Alien(idb, vemArInloggad).setVisible(true);
    }//GEN-LAST:event_btnGaTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytLosenord;
    private javax.swing.JButton btnGaTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passNuvarande;
    private javax.swing.JPasswordField passNytt;
    // End of variables declaration//GEN-END:variables
}
