/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaApplication1;

import oru.inf.InfDB;

/**
 *
 * @author kristofffer
 */
public class Inloggningssidan extends javax.swing.JFrame {
    
    InfDB idb;

    /**
     * Creates new form Inloggningssidan
     */
    public Inloggningssidan(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anvandarnamn = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        txtAnvandarnamn = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        loggaIn = new javax.swing.JToggleButton();
        txtAnvandarTyp = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        valjAnvandare = new javax.swing.JMenu();
        alienAnvandare = new javax.swing.JMenuItem();
        agentAnvandare = new javax.swing.JMenuItem();
        adminAnvandare = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        anvandarnamn.setText("Användarnamn");

        password.setText("Lösenord");

        txtAnvandarnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnvandarnamnActionPerformed(evt);
            }
        });

        txtPassword.setText("jPasswordField1");

        loggaIn.setText("Logga in");

        txtAnvandarTyp.setText("Välj användare");

        valjAnvandare.setText("Välj användare");

        alienAnvandare.setText("Alien");
        alienAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienAnvandareActionPerformed(evt);
            }
        });
        valjAnvandare.add(alienAnvandare);

        agentAnvandare.setText("Agent");
        agentAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentAnvandareActionPerformed(evt);
            }
        });
        valjAnvandare.add(agentAnvandare);

        adminAnvandare.setText("Admin");
        adminAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAnvandareActionPerformed(evt);
            }
        });
        valjAnvandare.add(adminAnvandare);

        jMenuBar1.add(valjAnvandare);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggaIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnvandarTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anvandarnamn)
                            .addComponent(password))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anvandarnamn)
                    .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggaIn)
                    .addComponent(txtAnvandarTyp))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnvandarnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnvandarnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnvandarnamnActionPerformed

    private void agentAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentAnvandareActionPerformed
        // TODO add your handling code here:
        txtAnvandarTyp.setText("Som Agent");
        
        
    }//GEN-LAST:event_agentAnvandareActionPerformed

    private void alienAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienAnvandareActionPerformed
        // TODO add your handling code here:
        txtAnvandarTyp.setText("Som Alien");
    }//GEN-LAST:event_alienAnvandareActionPerformed

    private void adminAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAnvandareActionPerformed
        // TODO add your handling code here:
        txtAnvandarTyp.setText("Som Admin");
    }//GEN-LAST:event_adminAnvandareActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adminAnvandare;
    private javax.swing.JMenuItem agentAnvandare;
    private javax.swing.JMenuItem alienAnvandare;
    private javax.swing.JLabel anvandarnamn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton loggaIn;
    private javax.swing.JLabel password;
    private javax.swing.JLabel txtAnvandarTyp;
    private javax.swing.JTextField txtAnvandarnamn;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JMenu valjAnvandare;
    // End of variables declaration//GEN-END:variables
}
